export const GETALL_CATEGORIES = "GETALL_CATEGORIES";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";
export const CREATE_ONE_CATEGORY = "CREATE_ONE_CATEGORY";
export const UPDATE_ONE_CATEGORY = "UPDATE_ONE_CATEGORY";
export const DELETE_ONE_CATEGORY = "DELETE_ONE_CATEGORY";